# Generated by Django 2.0.6 on 2018-06-16 12:51

import cloudinary.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quovadisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
                ('gallery_images', django.contrib.postgres.fields.ArrayField(base_field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'), size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
