# Generated by Django 2.0.6 on 2018-06-16 13:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quovadisapp', '0002_auto_20180616_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='gallery_images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
